dict_occupation_mother = {0:"student",
                          1:"representatives_of_the_legislative_power_and_executive_bodies_directors_directors_and_executive_managers",
                          2:"specialists_in_intellectual_and_scientific_activities",
                          3:"intermediate_level_technicians_and_professions",
                          4:"administrative_staff",
                          5:"personal_services_security_and_safety_workers_and_sellers",
                          6:"farmers_and_skilled_workers_in_agriculture_fisheries_and_forestry",
                          7:"skilled_workers_in_industry_construction_and_craftsmen",
                          8:"installation_and_machine_operators_and_assembly_workers",
                          9:"unskilled_workers",
                          10:"armed_forces_professions",
                          90:"other_situation",
                          99:"blank",
                          122:"health_professionals",
                          123:"teachers",
                          125:"Specialists in information and communication technologies (ICT)",
                          131:"intermediate_level_science_and_engineering_technicians_and_professions",
                          132:"technicians_and_professionals_of_intermediate_level_of_health",
                          134:"intermediate_level_technicians_from_legal_social_sports_cultural_and_similar_services",
                          141:"office_workers_secretaries_in_general_and_data_processing_operators",
                          143:"data_accounting_statistical_financial_services_and_registry-related_operators",
                          144:"other_administrative_support_staff",
                          151:"personal_service_workers",
                          152:"sellers",
                          153:"personal_care_workers_and_the_like",
                          171:"skilled_construction_workers_and_the_like_except_electricians",
                          173:"skilled workers in printing, precision instrument manufacturing, jewelers, artisans and the like",
                          175:"workers_in_food_processing_woodworking_clothing_and_other_industries_and_crafts",
                          191:"cleaning workers",
                          192:"unskilled_workers_in_agriculture_animal_production_fisheries_and_forestry",
                          193:"unskilled_workers_in_extractive_industry_construction_manufacturing_and_transport",
                          194:"meal_preparation_assistants"
                          }

dict_occupation_father = {0:"student",
                          1:"representatives_of_the_legislative_power_and_executive_bodies_directors_directors_and_executive_managers",
                          2:"specialists_in_intellectual_and_scientific_activities",
                          3:"intermediate_level_technicians_and_professions",
                          4:"administrative_staff",
                          5:"personal_services_security_and_safety_workers_and_sellers",
                          6:"farmers_and_skilled_workers_in_agriculture_fisheries_and_forestry",
                          7:"skilled_workers_in_industry_construction_and_craftsmen",
                          8:"installation_and_machine_operators_and_assembly_workers",
                          9:"unskilled_workers",
                          10:"armed_forces_professions",
                          90:"other_situation",
                          99:"blank",
                          101:"armed_forces_officers",
                          102:"armed_forces_sergeants",
                          103:"other_armed_forces_personnel",
                          112:"directors_of_administrative_and_commercial_services",
                          114:"hotel_catering_trade_and_other_services_directors",
                          121:"specialists_in_the_physical_sciences_mathematics_engineering_and_related_techniques",
                          122:"health_professionals",
                          123:"teachers",
                          124:"specialists_in_finance_accounting_administrative_organization_public_and_commercial_relations",
                          131:"intermediate_level_science_and_engineering_technicians_and_professions",
                          132:"technicians_and_professionals_of_intermediate_level_of_health",
                          134:"intermediate_level_technicians_from_legal_social_sports_cultural_and_similar_services",
                          135:"information_and_communication_technology_technicians",
                          141:"office_workers_secretaries_in_general_and_data_processing_operators",
                          143:"data_accounting_statistical_financial_services_and_registry-related_operators",
                          144:"other_administrative_support_staff",
                          151:"personal_service_workers",
                          152:"sellers",
                          153:"personal_care_workers_and_the_like",
                          154:"protection_and_security_services_personnel",
                          161:"market-oriented_farmers_and_skilled_agricultural_and_animal_production_workers",
                          163:"farmers_livestock_keepers_fishermen_hunters_and_gatherers_subsistence",
                          171:"skilled_construction_workers_and_the_like_except_electricians",
                          172:"skilled_workers_in_metallurgy_metalworking_and_similar",
                          174:"skilled_workers_in_electricity_and_electronics",
                          175:"workers_in_food_processing_woodworking_clothing_and_other_industries_and_crafts",
                          181:"fixed_plant_and_machine_operators",
                          182:"assembly_workers",
                          183:"vehicle_drivers_and_mobile_equipment_operators",
                          192:"unskilled_workers_in_agriculture_animal_production_fisheries_and_forestry",
                          193:"unskilled_workers_in_extractive_industry_construction_manufacturing_and_transport",
                          194:"meal_preparation_assistants",
                          195:"street_vendors_except_food_and_street_service_providers"
                          }

dict_qualifications_mother = {1:"secondary_education_12th_year_of_schooling_or_eq",
                              2:"higher_education_bachelors_degree",
                              3:"higher_education_degree",
                              4:"higher_education_masters",
                              5:"higher_education_doctorate",
                              6:"frequency_of_higher_education",
                              9:"12th_year_of_schooling_not_completed",
                              10:"11th_year_of_schooling_not_completed",
                              11:"7th_year_(old)",
                              12:"other_11th_year_of_schooling", 
                              14:"10th_year_of_schooling",
                              18:"general_commerce_course",
                              19:"basic_education_3rd_cycle_(9th/10th/11th year)_or_equiv",
                              22:"technical-professional_course",
                              26:"7th_year_of_schooling",
                              27:"2nd_cycle_of_the_general_high_school_course",
                              29:"9th_year_of_schooling_not_completed",
                              30:"8th_year_of_schooling",
                              34:"unknown",
                              35:"cant_read_or_write",
                              36:"can_read_without_having_a_4th_year_of_schooling",
                              37:"basic_education_1st_cycle_(4th/5th_year)_or_equiv",
                              38:"basic_education_2nd_cycle_(6th/7th/8th year)_or_equiv",
                              39:"technological_specialization_course",
                              40:"higher_education_degree_1st_cycle",
                              41:"specialized_higher_studies_course",
                              42:"professional_higher_technical_course",
                              43:"higher_education_master_2nd_cycle",
                              44:"higher_education:doctorate_3rd_cycle",
                              }

dict_qualifications_father = {1:"secondary_education_12th_year_of_schooling_or_eq",
                              2:"higher_education_bachelors_degree",
                              3:"higher_education_degree",
                              4:"higher_education_masters",
                              5:"higher_education_doctorate",
                              6:"frequency_of_higher_education",
                              9:"12th_year_of_schooling_not_completed",
                              10:"11th_year_of_schooling_not_completed",
                              11:"7th_year_(old)",
                              12:"other_11th_year_of_schooling",
                              13:"2nd_year_complementary_high_school_course",  
                              14:"10th_year_of_schooling",
                              18:"general_commerce_course",
                              19:"basic_education_3rd_cycle_(9th/10th/11th year)_or_equiv",
                              20:"complementary_high_school_course",
                              22:"technical-professional_course",
                              25:"complementary_high_school_course_not_concluded",
                              26:"7th_year_of_schooling",
                              27:"2nd_cycle_of_the_general_high_school_course",
                              29:"9th_year_of_schooling_not_completed",
                              30:"8th_year_of_schooling",
                              31:"general_course_of_administration_and_commerce",
                              33:"supplementary_accounting_and_administration",
                              34:"unknown",
                              35:"cant_read_or_write",
                              36:"can_read_without_having_a_4th_year_of_schooling",
                              37:"basic_education_1st_cycle_(4th/5th_year)_or_equiv",
                              38:"basic_education_2nd_cycle_(6th/7th/8th year)_or_equiv",
                              39:"technological_specialization_course",
                              40:"higher_education_degree_1st_cycle",
                              41:"specialized_higher_studies_course",
                              42:"professional_higher_technical_course",
                              43:"higher_education_master_2nd_cycle",
                              44:"higher_education:doctorate_3rd_cycle",
                              }

dict_nationality = {1:"portuguese",
                    2:"german",
                    6:"spanish",
                    11:"italian",
                    13:"dutch",
                    14:"english",
                    17:"lithuanian",
                    21:"angolan",
                    22:"cape_verdean",
                    24:"guinean",
                    25:"mozambican",
                    26:"santomean",
                    32:"turkish",
                    41:"brazilian",
                    62:"romanian",
                    100:"moldova",
                    101:"mexican",
                    103:"ukrainian",
                    105:"russian",
                    108:"cuban",
                    109:"colombian"
                    }

dict_previous_education = {1:"secondary_education",
                           2:"higher_education_bachelors_degree",
                           3:"higher_education_degree",
                           4:"higher_education_masters",
                           5:"higher_education_doctorate",
                           6:"frequency_of_higher_education",
                           9:"12th_year_of_schooling_not_completed",
                           10:"11th_year_of_schooling_not_completed",
                           12:"other_11th_year_of_schooling", 
                           14:"10th_year_of_schooling",
                           15:"10th_year_of_schooling_not_completed",
                           19:"basic_education_3rd_cycle_(9th/10th/11th year)_or_equiv",
                           38:"basic_education_2nd_cycle_(6th/7th/8th year)_or_equiv",
                           39:"technological_specialization_course",
                           40:"higher_education_degree_1st_cycle",
                           42:"professional_higher_technical_course",
                           43:"higher_education_master_2nd_cycle"
                           }

## nb 9991, 8014 evening attendance
dict_course = {33:"biofuel_production_technologies",
               171:"animation_and_multimedia_design",
               8014:"social_service",
               9003:"agronomy",
               9070:"communication_design",
               9085:"veterinary_nursing",
               9119:"informatics_engineering",
               9130:"equinculture",
               9147:"management",
               9238:"social_service",
               9254:"tourism",
               9500:"nursing",
               9556:"oral_hygiene",
               9670:"advertising_and_marketing_management",
               9773:"journalism_and_communication",
               9853:"basic_education",
               9991:"management"
               }

dict_marital_status = {1:"single", 
                       2:"married",
                       3:"widower",
                       4:"divorced",
                       5:"facto union",
                       6:"legally separated"
                       }

dict_application_mode = {1:"1st_phase_general_contingent",
                         2:"ordinance_no_612_93",
                         5:"1st_phase_special_contingent_azores_island",
                         7:"holders_of_other_higher_courses",
                         10:"ordinance_no_854B_99",
                         15:"international_student_bachelor",
                         16:"1st_phase_special_contingent_madeira_island",
                         17:"2nd_phase_general_contingent",
                         18:"3rd_phase_general_contingent",
                         26:"ordinance_no_533A_99_item_b2_different_plan",
                         27:"ordinance_no_533A_99_item_b3_other_institution",
                         39:"over_23_years_old",
                         42:"transfer",
                         43:"change_of_course",
                         44:"technological_specialization_diploma_holders",
                         51:"change_of_institution_course",
                         53:"short_cycle_diploma_holders",
                         57:"change_of_institution_course_international"
                         }

dicts = [dict_marital_status,
         dict_application_mode,
         dict_course,
         dict_previous_education,
         dict_nationality,
         dict_occupation_mother,
         dict_occupation_father,
         dict_qualifications_mother,
         dict_qualifications_father
         ]
columns_to_replace = ['marital_status',
                      'application_mode',
                      'course',
                      'previous_qualification',
                      'nationality',
                      "mothers_occupation",
                      "fathers_occupation",
                      "mothers_qualification",
                      "fathers_qualification"
                      ]

# Define different 'class' of occupations

# Blue-Collar: 'Working class', primarily manual labour.
# Light-Blue_collar: Atisans. For example, jewelrer. 
# White-Collar: Salaried professional, primarily office worker.
# Gold-Collar: Specialised work. Doctors, lawyers, engineers, pilots, scientists.
# Pink-Collar: Nurse, secretary, elementary school teacher, 'traditionally female occupations' - generally encompases service-focused occupations.
# Grey-Collar: Arbitray label used to designate occupations related to armed forces, or similar

dict_collars = {"unskilled"     : [ 'cleaning workers',
                                    'unskilled_workers',
                                    'installation_and_machine_operators_and_assembly_workers',
                                    'unskilled_workers_in_agriculture_animal_production_fisheries_and_forestry',
                                    'unskilled_workers_in_extractive_industry_construction_manufacturing_and_transport',
                                    'assembly_workers',
                                    'fixed_plant_and_machine_operators',
                                    'vehicle_drivers_and_mobile_equipment_operators',
                                    'other_armed_forces_personnel',
                                    'sellers',
                                    'meal_preparation_assistants',
                                    'personal_care_workers_and_the_like', 
                                    'personal_service_workers',
                                    'personal_services_security_and_safety_workers_and_sellers',
                                    'street_vendors_except_food_and_street_service_providers',
                                    ],

                "skilled"       : [ 'farmers_and_skilled_workers_in_agriculture_fisheries_and_forestry',
                                    'farmers_livestock_keepers_fishermen_hunters_and_gatherers_subsistence',
                                    'market-oriented_farmers_and_skilled_agricultural_and_animal_production_workers',
                                    'skilled_construction_workers_and_the_like_except_electricians',
                                    'skilled_workers_in_industry_construction_and_craftsmen',
                                    'skilled_workers_in_electricity_and_electronics',
                                    'skilled_workers_in_metallurgy_metalworking_and_similar',
                                    'armed_forces_sergeants',
                                    'protection_and_security_services_personnel',
                                    'skilled workers in printing, precision instrument manufacturing, jewelers, artisans and the like',
                                    'workers_in_food_processing_woodworking_clothing_and_other_industries_and_crafts',    
                                    'administrative_staff',
                                    'office_workers_secretaries_in_general_and_data_processing_operators',
                                    'other_administrative_support_staff',
                                    'intermediate_level_science_and_engineering_technicians_and_professions',
                                    'intermediate_level_technicians_and_professions',
                                    'intermediate_level_technicians_from_legal_social_sports_cultural_and_similar_services',
                                    'technicians_and_professionals_of_intermediate_level_of_health',
                                    'information_and_communication_technology_technicians',
                                    ],

                "professional"  : [ 'armed_forces_professions',
                                    'health_professionals',
                                    'data_accounting_statistical_financial_services_and_registry-related_operators',
                                    'specialists_in_information_and_communication_technologies_ict',
                                    'specialists_in_intellectual_and_scientific_activities',
                                    'specialists_in_finance_accounting_administrative_organization_public_and_commercial_relations',
                                    'specialists_in_the_physical_sciences_mathematics_engineering_and_related_techniques',
                                    'teachers',
                                    ],

                "managerial"    : [ 'armed_forces_officers', 
                                    'representatives_of_the_legislative_power_and_executive_bodies_directors_directors_and_executive_managers',
                                    'directors_of_administrative_and_commercial_services',
                                    'hotel_catering_trade_and_other_services_directors',
                                   ],

                "other"         : ['blank',
                                   'other_situation',
                                   'student',],
                }

inverse = { v: k for k, l in dict_collars.items() for v in l }

# Create groupings for education (to reduce feature space)
#https://eurydice.eacea.ec.europa.eu/national-education-systems/portugal/overview#:~:text=The%20Portuguese%20education%20system%20is%20divided%20in%20pre%2Dschool%20education,15%20to%2018%20years%20old).

# 
# Upper secondary: Grades 10, 11, 12

dict_education = {  "basic":[   "cant_read_or_write", 
                                'can_read_without_having_a_4th_year_of_schooling',
                                '7th_year_(old)',
                                '7th_year_of_schooling',
                                '8th_year_of_schooling',
                                '9th_year_of_schooling_not_completed',
                                '10th_year_of_schooling_not_completed',
                                'basic_education_1st_cycle_(4th/5th_year)_or_equiv',
                                'basic_education_2nd_cycle_(6th/7th/8th year)_or_equiv'
                                ],
                    "upper_secondary":[         '10th_year_of_schooling',
                                                '11th_year_of_schooling_not_completed',
                                                '12th_year_of_schooling_not_completed',
                                                '2nd_cycle_of_the_general_high_school_course',
                                                'other_11th_year_of_schooling',
                                                'secondary_education_12th_year_of_schooling_or_eq',
                                                'basic_education_3rd_cycle_(9th/10th/11th year)_or_equiv',
                                                '2nd_year_complementary_high_school_course',
                                                'complementary_high_school_course',
                                                'complementary_high_school_course_not_concluded',
                                                'secondary_education'
                                                ],
                    "higher_education":[    'higher_education_bachelors_degree', 
                                            'higher_education_degree',
                                            'higher_education_degree_1st_cycle',
                                            'higher_education_master_2nd_cycle', 
                                            'higher_education_masters',
                                            'higher_education_doctorate_3rd_cycle',
                                            'higher_education_doctorate',],

                    "other":['general_commerce_course',
                             'technological_specialization_course',
                             'technical-professional_course',
                             'specialized_higher_studies_course',
                             'frequency_of_higher_education',
                             'professional_higher_technical_course',
                             'general_course_of_administration_and_commerce',
                             'supplementary_accounting_and_administration'],
                    }

#['unknown']
inverse_education = { v: k for k, l in dict_education.items() for v in l }